### ISSUE TITLE
Captcha image is not displaying when the user click on checkbox(i'm not a robot).

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#93] opened 2019-02-04 09:28 UTC
Environment :- Windows 7
Module: Sign up
Credentials :-john_k@mailinator.com /11111111
Priority :- Medium

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3. Click on sign up
4 Click on checkbox(i'm not a robot)
5 observe

Note :- This defect is reproducible sometimes, not all the time.

Actual result: Captcha image is not displaying when the user click on checkbox(i'm not a robot).
Expected result: Captcha image should be display when the user click on checkbox(i'm not a robot).

Video URL : https://drive.google.com/file/d/1H7u8Rp_lcGLeL8bXFUQcHnMZEqByhSku/view?usp=sharing

**Comment by acipher** [comment] 2019-03-15 07:44
Unable to reproduce the issue. @javulorg can you please validate?

**Comment by javulorg** [comment] 2019-03-17 01:20
@Shivakumarbv, I couldnt view the video link.
I tried a few times and I couldnt reproduce it also. I see the note that its intermittent and doesnt always appear. Closing for now. Reopen if you see it again.

**Closed by javulorg** 2019-03-17 01:20 UTC
