### ISSUE TITLE
User is able to create multiple Javul accounts using the same Gmail ID.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#125] opened 2019-02-06 04:57 UTC
Environment :- Windows 7
Module :- Signup
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and click on Signup
2.At Email Address field, enter r6.pulsefbi@gmail.com and observe.
3."Email already exist" is displayed.
4.Now from the same Email ID, shift the dot and enter.
Example:- r6pulse.fbi@gmail.com 
5.Click on Signup and Observe.

Note :- Gmail has a unique feature, when user enters an email ID, by shifting the dot within the address and enter the password, it will consider it as same email ID.
For Example :- Original Email Id is :- r6.pulsefbi@gmail.com
But when user login with (r6pulse.fbi@gmail.com, r.6pulsefbi@gmail.com, r6p.ulsefbi@gmail.com, r6p.ulsefbi@gmail.com, r6pu.lsefbi@gmail.com, r6pul.sefbi@gmail.com, r6puls.efbi@gmail.com, r6pulsef.bi@gmail.com, r6pulsefb.i@gmail.com, etc...) all these email ID's, Gmail will always login to the original email ID (Which is r6.pulsefbi@gmail.com). 
But, Javul is considering it as separate email address. When user creates Javul accounts with above listed email IDs and request for forgot password link or does any payments or financial transactions, all the emails from Javul will go to one single gmail ID (Which is r6.pulsefbi@gmail.com). 
So, whenever user create Javul account with Gmail ID by shifting dot, user should not be able to create multiple Javul accounts. 

Actual Result :- User is able to create multiple Javul accounts using the same Gmail ID.
Expected Result :- User should not be able to create multiple Javul accounts using the same Gmail ID. Validation/Error message should be displayed. 

Video URL :- https://drive.google.com/file/d/1g7XG9OJE3x6YXJLPlgiSm4lpoJhqnu_u/view?usp=sharing

**Comment by acipher** [comment] 2019-03-16 08:04
@javulorg  can you please validate this?. I think any email can be fine as long as it's format is correct i don't see any format issue on above mention emails. Do we need to make any changes on this still?

**Comment by javulorg** [comment] 2019-03-17 00:22
The issue is that a user can create multiple accounts using the same Gmail address.
I was thinking that the solution could be to remove Dots when we have a gmail address and then store that value in the database. However I'm not sure if its the recommended solution that other websites also follow. Since this is a minor issue for now, I'll close it and will make a note of it to address some other time.

**Closed by javulorg** 2019-03-17 00:22 UTC
