### ISSUE TITLE
"Whoops, looks like something went wrong." ErrorException an error message is displaying when user clicks on the unit categories.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#124] opened 2019-02-06 04:29 UTC
Environment :- Windows 7
Module: Units/Objectives
Credentials :- [john_k@mailinator.com]/11111111
priority :Major

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on existing created objectives
4. Now click on unit categories(SOFTWARE)
5 Observe

Actual result: "Whoops, looks like something went wrong." ErrorException an error message is displaying when user clicks on the unit categories.

Expected result: When user click on edit unit categories, error message should not be displayed.

Video URL: https://drive.google.com/file/d/14-2MAg4HIExeWFAJQqtaN5fUO44sBpBx/view?usp=sharing

**Comment by acipher** [comment] 2019-02-25 09:24
Dummy ticket created can you please check #99.

**Comment by javulorg** [comment] 2019-03-01 04:25
Thanks, I'll close this as a duplicate of #99

**Closed by javulorg** 2019-03-01 04:25 UTC
